- name: Generate htpasswd password
  set_fact:
    htpasswd_pass: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters') }}"

- name: Encrypt htpasswd password
  command: openssl passwd -apr1 {{ htpasswd_pass }}
  register: htpasswd_encrypted

- name: Save output to htpasswd
  copy: content="{{ app_name }}:{{ htpasswd_encrypted.stdout }}" dest=/etc/nginx/.htpasswd-{{ app_name }}
