name: devops-task

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: development

    steps:
      - name: Deploy to development
        run: |
           git pull
           npm install
           pm2 restart devops-task
